In [1]:
import pandas as pd
from datetime import datetime

In [24]:
data=pd.read_csv('../Datos en bruto/Google Trends/Gripe/multiTimeline.csv',skiprows=2,sep=",")
data.head()

       Semana  gripe: (España)
0  2020-12-27               67
1  2021-01-03               53
2  2021-01-10               53
3  2021-01-17               58
4  2021-01-24               51

In [25]:
for i in range(1,13):
    df=pd.read_csv('../Datos en bruto/Google Trends/Gripe/multiTimeline ('+str(i)+').csv',skiprows=2,sep=",")
    data=pd.concat([data,df])

In [26]:
data=data.drop_duplicates(subset='Semana',keep='last')

In [27]:
data.set_index('Semana',inplace=True)
data=data.sort_index()
data=data.rename({'gripe: (España)':'gripe_trends'},axis=1)
data

            gripe_trends
Semana
2012-12-30            43
2013-01-06            47
2013-01-13            56
2013-01-20            65
2013-01-27            82
...                  ...
2025-04-06            14
2025-04-13            10
2025-04-20            10
2025-04-27             8
2025-05-04             9

[645 rows x 1 columns]

In [28]:
#Exportamos los datos relativos a las busquedas de gripe en España
data.to_csv('flu_trends.csv',index=True,encoding='utf-8')